### ISSUE TITLE
ValueError: level must be >= 0

### ISSUE THREAD

**Issue by yaseenox** [stalkerg/python-readability#3]
Hi, I got the following error:

  File "test.py", line 1, in <module>
    from readability.readability import Document
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/readability/__init__.py", line 1, in <module>
    from .readability import Document
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/readability/readability.py", line 5, in <module>
    from lxml.etree import tostring
  File "lxml.etree.pyx", line 48, in init lxml.etree (src/lxml/lxml.etree.c:159821)
ValueError: level must be >= 0

**The Code:**

from readability.readability import Document
import urllib

html = urllib.urlopen('http://www.bbc.com/news/business-37618618').read()
doc = Document(html)
doc.parse(["summary", "short_title"])
readable_article = doc.summary()
readable_title = doc.short_title()
print(readable_title)
print(readable_article)

**Comment by yaseenox** [comment]
seems like the installer automatically Uninstalling lxml-3.6.4 and install lxml 2.3.6

**Comment by stalkerg** [comment]
Thanks for this bug I will try fix for latest lxml.

**Comment by yaseenox** [comment]
Also urlopen is part of urllib.request in python3

**Comment by stalkerg** [comment]
>Also urlopen is part of urllib.request in python3
Forgot fix after port make. And I suppose better use "request" library.

**Comment by stalkerg** [comment]
Please try again. :) I clean up many things.
